try {
    panic("111") 
} catch err {
    print("222")
}